# Stage 1: Build the application
FROM python:3 AS builder

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir Flask

# Stage 2: Create the final image
FROM python:3-slim

WORKDIR /app

# Copy only necessary files from the builder stage
COPY --from=builder /app .

# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Expose the port your app runs on
EXPOSE 5000

# Command to run your application
CMD ["python", "app.py"]

