version: '3'
services:
  todo-notesapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - Database:/data/database
    ports:
      - "5000:5000"

volumes:
  Database:
    external: true

